---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/labels.yaml@3b51cf1b981d0150269cbcac88ec5f423a42b87d
