---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

permissions: {}

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/pr-labels.yaml@3b51cf1b981d0150269cbcac88ec5f423a42b87d
